### ISSUE TITLE
@mediapipe/face_detection

### ISSUE THREAD

**Issue by abenoov** [spencer17x/arca#9]
Hello! Can you add support for the module "@mediapipe/face_detection"?

**Comment by spencer17x** [comment]
use vite-plugin-mediapipe@0.1.0-beta.0: pnpm add vite-plugin-mediapipe@0.1.0-beta.0

**Comment by abenoov** [comment]
> use vite-plugin-mediapipe@0.1.0-beta.0: pnpm add vite-plugin-mediapipe@0.1.0-beta.0

Thanks a lot, it works! When will there be a stable version? I'm going to use it in production.

**Comment by spencer17x** [comment]
@abenoov I will release the new version and let you know as soon as possible.

**Comment by spencer17x** [comment]
vite-plugin-mediapipe@0.1.0 has been published：
https://github.com/spencer17x/arca/blob/main/packages/vite-plugin/vite-plugin-mediapipe/CHANGELOG.md
@abenoov
